# UNIT 3 | PY101: INTRO TO PYTHON I

## 3.2 - LISTS

In [56]:
a = [3,10,-1] # define list with values 3, 10 and -1

print(a)

[3, 10, -1]


In [57]:
a.append("hello") #insert value "hello" at the end of the list

print(a)

[3, 10, -1, 'hello']


In [58]:
a.pop() # deletes the last item in the list

print(a)

[3, 10, -1]


In [59]:
a[0] = 4 #reassigns the first item from 3 to 4

print(a)

[4, 10, -1]


In [60]:
a.insert(0,"new first item") #insert string value at index 0

print(a)

['new first item', 4, 10, -1]


In [61]:
# removing items using .remove() string method
a.remove(a[0])

print(a)

[4, 10, -1]


In [62]:
# removing items using del keyword
del a[0]

print(a)

[10, -1]


In [54]:
a.insert(10,2) # specifying an index out of range - python automatically gives it a lower index?

#print(a[10])
#print(a[-1])

In [44]:
# Since assigning a = b actually assigns b to whatever value a was most RECENTLY assigned to
# you can't swap items in a list using simple reassignment, as seen below:

b = ["banana","apple","orange"]

b[0]=b[2] # now b[0] = "orange"
b[1]=b[0] # since b[0] most recently assigned to "orange", then b[1] will also be assigned to that
b[2]=b[1] # same thing happens here


# result is they all get the original value of b[2] instead of swapping values:
print(b)

['orange', 'orange', 'orange']


In [45]:
# One way of swapping values requires a temporary placeholder for one of the variables:

b = ["banana","apple","orange"]

temp_b0 = b[0]
b[0]=b[2]
b[2]=b[1]
b[1] = temp_b0

print(b)


['orange', 'banana', 'apple']


In [47]:
# Another way of swapping values is something like unpacking?

b = ["banana","apple","orange"]

b[0],b[1],b[2] = b[2],b[0],b[1]

print(b)

['orange', 'banana', 'apple']


## Functions & Packages

### NumPy

In [74]:
import numpy as np

zero_dim = np.array(3845)
one_dim = np.array([34,21,7])
two_dim = np.array([[2,4],[6,3]])
three_dim = np.array([[[2,3,4],[5,6,7]],[[3,4,1],[6,2,6]],[[9,3,5],[1,3,2]]])

arrays = [zero_dim,one_dim,two_dim,three_dim]

In [86]:
for a in arrays:
    print(f"{a.ndim}-dimensional array:\n\n{a}\n\n\n")

0-dimensional array:

3845



1-dimensional array:

[34 21  7]



2-dimensional array:

[[2 4]
 [6 3]]



3-dimensional array:

[[[2 3 4]
  [5 6 7]]

 [[3 4 1]
  [6 2 6]]

 [[9 3 5]
  [1 3 2]]]





In [95]:
b = np.array([4], ndmin=2)

In [115]:
cubic_matrix = np.random.rand(2,2,2)
cubic_zeros = np.zeros((2,2,2))
cubic_full = np.full((2,2,2),5)
cubic_ones = np.ones((2,2,2))
print(f"{cubic_matrix}\n\n{cubic_zeros}\n\n{cubic_full}\n\n{cubic_ones}")

[[[0.66461107 0.36203778]
  [0.87916353 0.51338581]]

 [[0.0568425  0.47762111]
  [0.58706278 0.65212653]]]

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]

[[[5 5]
  [5 5]]

 [[5 5]
  [5 5]]]

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [118]:
# Attributes
print(cubic_full.shape) # returns tuple with number of items spanning each dimension
print(cubic_full.size) # total number of items in array
print(cubic_full.dtype) # what types of data objects comprise the items of array

(2, 2, 2)
8
int64


In [129]:
mixed = np.array([[2,3,4],[0.1345,385,9.13],["hello",67,"okay"]])
stringray = np.full((2,2,2),"B")
print(stringray,"\n\n",stringray.dtype)
print(mixed,"\n\n",mixed.dtype)

[[['B' 'B']
  ['B' 'B']]

 [['B' 'B']
  ['B' 'B']]] 

 <U1
[['2' '3' '4']
 ['0.1345' '385' '9.13']
 ['hello' '67' 'okay']] 

 <U32


In [135]:
r = np.random.rand(3,3,3)

print(r)

[[[0.28253222 0.73872572 0.65330356]
  [0.52444563 0.07969556 0.7127261 ]
  [0.45774588 0.05427697 0.7507664 ]]

 [[0.64866425 0.94316782 0.95306996]
  [0.26409158 0.4990588  0.55046182]
  [0.31188666 0.6132854  0.70929749]]

 [[0.31877939 0.65486795 0.59067091]
  [0.50938422 0.45909412 0.18535969]
  [0.25829513 0.24855194 0.34130865]]]


In [140]:
print(f"{r[0]}\n\n{r[0][0]}\n\n{r[0][0][0:2]}")

[[0.28253222 0.73872572 0.65330356]
 [0.52444563 0.07969556 0.7127261 ]
 [0.45774588 0.05427697 0.7507664 ]]

[0.28253222 0.73872572 0.65330356]

[0.28253222 0.73872572]


In [142]:
s = np.random.rand(3,3,3)*10
print(s)

[[[2.12447225 7.29066426 9.34997445]
  [9.25745699 9.67446042 3.22665703]
  [4.16027514 6.24427415 5.044845  ]]

 [[6.62154361 2.08064498 6.41469841]
  [4.40128501 9.40219429 0.29036262]
  [0.81179368 5.7388288  6.55865397]]

 [[3.21516494 9.98269617 9.0812934 ]
  [2.51370282 4.69944821 5.75239265]
  [8.87461929 9.06872462 8.18238345]]]


In [151]:
print(np.add(r,s) == r + s)
print(np.subtract(s,r) == s - r)

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]


In [152]:
np.multiply(r,s) == r * s
print(r * s)

[[[0.60023186 5.38580121 6.10837155]
  [4.85503289 0.77101154 2.29972267]
  [1.9043488  0.33892025 3.78750009]]

 [[4.29515863 1.96239738 6.11365633]
  [1.16234231 4.69224783 0.15983354]
  [0.25318762 3.51953989 4.65203678]]

 [[1.02492833 6.53734781 5.36405585]
  [1.28044055 2.15748904 1.06626174]
  [2.29227092 2.25404906 2.79271822]]]


In [159]:
dp = np.dot(r,s)
cp = np.cross(r,s)
print(r.shape, s.shape)
print(dp.shape, cp.shape)

(3, 3, 3) (3, 3, 3)
(3, 3, 3, 3) (3, 3, 3)


In [160]:
r

array([[[0.28253222, 0.73872572, 0.65330356],
        [0.52444563, 0.07969556, 0.7127261 ],
        [0.45774588, 0.05427697, 0.7507664 ]],

       [[0.64866425, 0.94316782, 0.95306996],
        [0.26409158, 0.4990588 , 0.55046182],
        [0.31188666, 0.6132854 , 0.70929749]],

       [[0.31877939, 0.65486795, 0.59067091],
        [0.50938422, 0.45909412, 0.18535969],
        [0.25829513, 0.24855194, 0.34130865]]])

In [161]:
s

array([[[2.12447225, 7.29066426, 9.34997445],
        [9.25745699, 9.67446042, 3.22665703],
        [4.16027514, 6.24427415, 5.044845  ]],

       [[6.62154361, 2.08064498, 6.41469841],
        [4.40128501, 9.40219429, 0.29036262],
        [0.81179368, 5.7388288 , 6.55865397]],

       [[3.21516494, 9.98269617, 9.0812934 ],
        [2.51370282, 4.69944821, 5.75239265],
        [8.87461929, 9.06872462, 8.18238345]]])

In [162]:
np.dot(r,s)

array([[[[10.15687599, 13.2860268 ,  8.32109875],
         [ 5.65248956, 11.28268926,  6.31164927],
         [ 8.56314495, 12.21666662, 12.16077859]],

        [[ 4.81708508,  9.04502571,  8.75629619],
         [ 4.40198904,  5.93071136,  8.06182502],
         [ 8.21168293, 12.07342327, 11.05288304]],

        [[ 4.59832985,  8.55036305,  8.24254551],
         [ 3.8793401 ,  5.77124904,  7.87607875],
         [ 8.27093059, 11.6331035 , 10.61220557]]],


       [[[14.07443794, 19.80506307, 13.91636345],
         [ 9.22000518, 15.68699239, 10.68570227],
         [12.91453918, 19.55091543, 19.11456585]],

        [[ 7.47114326, 10.19076217,  6.85653566],
         [ 4.39205536,  8.40073479,  5.44926445],
         [ 6.98872259,  9.97363364,  9.77316498]],

        [[ 9.29093042, 12.63611414,  8.47328979],
         [ 5.34021814, 10.48569069,  6.83077077],
         [ 8.83912943, 12.42799628, 12.16393666]]],


       [[[ 9.1970034 , 12.34791873,  8.07345667],
         [ 5.47257508, 10.21022172

In [163]:
v1 = np.array([1,2,3])
v2 = np.array([6,2.5,6.79])
np.dot(v1,v2)

31.37

In [187]:
# Statistical Functions - SAP LEMM

sqrt = np.sqrt(25)
ab = np.abs(-42)
power = np.power(2,10) # takes first argument as base, and second argument as exponent
log = np.log(25)
exp = np.exp([1,4]) # converts each item of the array to e to the power of the original item value
mins = np.min(v1)
maxs = np.max(v1)

print(sqrt,ab,power,log,exp,mins,maxs)

5.0 42 1024 3.2188758248682006 [ 2.71828183 54.59815003] 1 3


In [166]:
np.power(2,10) == 2**10

True

In [177]:
print(np.exp([2,10]))

print(np.array([np.e ** 2, np.e ** 10]))

[7.38905610e+00 2.20264658e+04]
[7.38905610e+00 2.20264658e+04]


In [194]:
np.append(v1,10) #note: doesn't permanently change the orignal array

array([ 1,  2,  3, 10])

In [195]:
np.insert(v1,2,4) # see that the 10 disappeared

array([1, 2, 4, 3])

In [201]:
r.sort()
r

array([[[0.28253222, 0.65330356, 0.73872572],
        [0.07969556, 0.52444563, 0.7127261 ],
        [0.05427697, 0.45774588, 0.7507664 ]],

       [[0.64866425, 0.94316782, 0.95306996],
        [0.26409158, 0.4990588 , 0.55046182],
        [0.31188666, 0.6132854 , 0.70929749]],

       [[0.31877939, 0.59067091, 0.65486795],
        [0.18535969, 0.45909412, 0.50938422],
        [0.24855194, 0.25829513, 0.34130865]]])

In [190]:
import math
math.log(25) == np.log(25)

True

In [228]:
del r[0] # doesn't work like a list!

ValueError: cannot delete array elements

In [213]:
print(two_dim)

[[2 4]
 [6 3]]


In [217]:
np.delete(two_dim, 0, axis=0) # axis=0 means rows, so it deletes the first row

array([[6, 3]])

In [216]:
np.delete(two_dim, 0, axis=1) # axis=1 means columns

array([[4],
       [3]])

In [221]:
np.delete(two_dim,[1,1]) # ???

array([2, 6, 3])

In [215]:
print(three_dim) # 3D array composed of three 2D arrays

[[[2 3 4]
  [5 6 7]]

 [[3 4 1]
  [6 2 6]]

 [[9 3 5]
  [1 3 2]]]


In [222]:
np.delete(three_dim,1,axis=0) # axis 0 means delete the second of the three 2D arrays

array([[[2, 3, 4],
        [5, 6, 7]],

       [[9, 3, 5],
        [1, 3, 2]]])

In [223]:
np.delete(three_dim,1,axis=1) # axis 1 means delete the second of the two 1D arrays within each 2D array

array([[[2, 3, 4]],

       [[3, 4, 1]],

       [[9, 3, 5]]])

In [224]:
np.delete(three_dim,1,axis=2) # axis 2 means delete the second of the three items within each 1D array

array([[[2, 4],
        [5, 7]],

       [[3, 1],
        [6, 6]],

       [[9, 5],
        [1, 2]]])

In [225]:
np.save("3D-Array",three_dim) # saves to /path/to/jupyter/notebook/3D-Array.npy

In [226]:
np.load("3D-Array.npy")

array([[[2, 3, 4],
        [5, 6, 7]],

       [[3, 4, 1],
        [6, 2, 6]],

       [[9, 3, 5],
        [1, 3, 2]]])

# UNIT 5 | PY102: INTRO TO PYTHON II

## 

## 5.1 - Matplotlib

## 5.2 - Dictionaries & Pandas

## 5.3 - Logic, Control Flow & Filtering

Within the bool() function, empty strings evaluate to False while all other strings evaluate to True.

Within the str() function, all booleans get converted to a string of the same name.  In the case of False, the string is 'False', which is not an empty string - i.e., the boolean of the string of False is True!

In [263]:
bool(str(False))

True

### DataCamp - Intermediate Python
Filtering pandas DataFrames

In [330]:
import os, pandas as pd, numpy as np, matplotlib.pyplot as plt
os.listdir('.')

['NotebookTest.ipynb',
 'script.py',
 'Springboard-Curriculum.ipynb',
 '.git',
 'BRICS_Series - Metadata.csv',
 '3D-Array.npy',
 '.ipynb_checkpoints',
 'BRICS_Data.csv',
 'Untitled.ipynb',
 'subdir']

In [331]:
pd.read_csv('BRICS_Data.csv')

Series Name        Series Code  \
0                               GDP growth (annual %)  NY.GDP.MKTP.KD.ZG   
1                               GDP growth (annual %)  NY.GDP.MKTP.KD.ZG   
2                               GDP growth (annual %)  NY.GDP.MKTP.KD.ZG   
3                               GDP growth (annual %)  NY.GDP.MKTP.KD.ZG   
4                               GDP growth (annual %)  NY.GDP.MKTP.KD.ZG   
5   General government final consumption expenditu...     NE.CON.GOVT.ZS   
6   General government final consumption expenditu...     NE.CON.GOVT.ZS   
7   General government final consumption expenditu...     NE.CON.GOVT.ZS   
8   General government final consumption expenditu...     NE.CON.GOVT.ZS   
9   General government final consumption expenditu...     NE.CON.GOVT.ZS   
10                                                NaN                NaN   
11                                                NaN                NaN   
12                                                NaN                NaN   
13   Data from database: World Development Indicators                NaN   
14                           Last Updated: 11/13/2024                NaN   

          Country Name Country Code  2009 [YR2009]  2010 [YR2010]  \
0               Brazil          BRA      -0.125812       7.528226   
1   Russian Federation          RUS      -7.799994       4.500000   
2                India          IND       7.861889       8.497585   
3                China          CHN       9.398726      10.635871   
4         South Africa          ZAF      -1.538089       3.039733   
5               Brazil          BRA      19.650638      19.016858   
6   Russian Federation          RUS      20.786597      18.725055   
7                India          IND      11.459667      11.007608   
8                China          CHN      14.752976      14.587021   
9         South Africa          ZAF      17.793633      17.996064   
10                 NaN          NaN            NaN            NaN   
11                 NaN          NaN            NaN            NaN   
12                 NaN          NaN            NaN            NaN   
13                 NaN          NaN            NaN            NaN   
14                 NaN          NaN            NaN            NaN   

    2011 [YR2011]  2012 [YR2012]  
0        3.974423       1.921176  
1        4.300029       4.024086  
2        5.241316       5.456388  
3        9.550832       7.863736  
4        3.168556       2.396232  
5       18.669257      18.530103  
6       17.625512      17.967238  
7       11.084462      10.683856  
8       15.238865      15.756078  
9       18.195143      18.820545  
10            NaN            NaN  
11            NaN            NaN  
12            NaN            NaN  
13            NaN            NaN  
14            NaN            NaN

In [332]:
df = pd.read_csv('BRICS_Data.csv')
print(df)

                                          Series Name        Series Code  \
0                               GDP growth (annual %)  NY.GDP.MKTP.KD.ZG   
1                               GDP growth (annual %)  NY.GDP.MKTP.KD.ZG   
2                               GDP growth (annual %)  NY.GDP.MKTP.KD.ZG   
3                               GDP growth (annual %)  NY.GDP.MKTP.KD.ZG   
4                               GDP growth (annual %)  NY.GDP.MKTP.KD.ZG   
5   General government final consumption expenditu...     NE.CON.GOVT.ZS   
6   General government final consumption expenditu...     NE.CON.GOVT.ZS   
7   General government final consumption expenditu...     NE.CON.GOVT.ZS   
8   General government final consumption expenditu...     NE.CON.GOVT.ZS   
9   General government final consumption expenditu...     NE.CON.GOVT.ZS   
10                                                NaN                NaN   
11                                                NaN                NaN   
12          

In [333]:
df = df.drop([i for i in range(10,15)])

In [334]:
df

Series Name        Series Code  \
0                              GDP growth (annual %)  NY.GDP.MKTP.KD.ZG   
1                              GDP growth (annual %)  NY.GDP.MKTP.KD.ZG   
2                              GDP growth (annual %)  NY.GDP.MKTP.KD.ZG   
3                              GDP growth (annual %)  NY.GDP.MKTP.KD.ZG   
4                              GDP growth (annual %)  NY.GDP.MKTP.KD.ZG   
5  General government final consumption expenditu...     NE.CON.GOVT.ZS   
6  General government final consumption expenditu...     NE.CON.GOVT.ZS   
7  General government final consumption expenditu...     NE.CON.GOVT.ZS   
8  General government final consumption expenditu...     NE.CON.GOVT.ZS   
9  General government final consumption expenditu...     NE.CON.GOVT.ZS   

         Country Name Country Code  2009 [YR2009]  2010 [YR2010]  \
0              Brazil          BRA      -0.125812       7.528226   
1  Russian Federation          RUS      -7.799994       4.500000   
2               India          IND       7.861889       8.497585   
3               China          CHN       9.398726      10.635871   
4        South Africa          ZAF      -1.538089       3.039733   
5              Brazil          BRA      19.650638      19.016858   
6  Russian Federation          RUS      20.786597      18.725055   
7               India          IND      11.459667      11.007608   
8               China          CHN      14.752976      14.587021   
9        South Africa          ZAF      17.793633      17.996064   

   2011 [YR2011]  2012 [YR2012]  
0       3.974423       1.921176  
1       4.300029       4.024086  
2       5.241316       5.456388  
3       9.550832       7.863736  
4       3.168556       2.396232  
5      18.669257      18.530103  
6      17.625512      17.967238  
7      11.084462      10.683856  
8      15.238865      15.756078  
9      18.195143      18.820545

In [335]:
sdf = df.loc[0:4,['Country Code','Country Name',df.columns[-1]]]
print(sdf)

  Country Code        Country Name  2012 [YR2012]
0          BRA              Brazil       1.921176
1          RUS  Russian Federation       4.024086
2          IND               India       5.456388
3          CHN               China       7.863736
4          ZAF        South Africa       2.396232


In [336]:
sdf.columns = ['Code','Country','GDP(2012)']
sdf['Code'] = ['BR','RU','IN','CH','SA']
sdf.loc[1,'Country'] = 'Russia'
sdf.set_index = 'Code'
sdf

Code       Country  GDP(2012)
0   BR        Brazil   1.921176
1   RU        Russia   4.024086
2   IN         India   5.456388
3   CH         China   7.863736
4   SA  South Africa   2.396232

In [337]:
brics = sdf
area = [8.516,17.100,3.286,9.597,1.221]
pop = [200.40,143.50,1251.00,1657.00,52.98]
cap = ['Brasilia','Moscow','New Delhi','Beijing','Pretoria']

brics['capital']=cap
brics['area']=area
brics['population']=pop
brics

Code       Country  GDP(2012)    capital    area  population
0   BR        Brazil   1.921176   Brasilia   8.516      200.40
1   RU        Russia   4.024086     Moscow  17.100      143.50
2   IN         India   5.456388  New Delhi   3.286     1251.00
3   CH         China   7.863736    Beijing   9.597     1657.00
4   SA  South Africa   2.396232   Pretoria   1.221       52.98

In [338]:
brics.index = brics['Code']
brics.drop(columns='Code',inplace=True)

In [342]:
brics.index.name = None
brics

Country  GDP(2012)    capital    area  population
BR        Brazil   1.921176   Brasilia   8.516      200.40
RU        Russia   4.024086     Moscow  17.100      143.50
IN         India   5.456388  New Delhi   3.286     1251.00
CH         China   7.863736    Beijing   9.597     1657.00
SA  South Africa   2.396232   Pretoria   1.221       52.98

In [343]:
brics['area']

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [344]:
brics['area'] > 8

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [346]:
is_huge = brics['area'] > 8
brics[is_huge]

Country  GDP(2012)   capital    area  population
BR  Brazil   1.921176  Brasilia   8.516       200.4
RU  Russia   4.024086    Moscow  17.100       143.5
CH   China   7.863736   Beijing   9.597      1657.0

Note that is_huge is a pandas **series** object.  So a series can be used to specify the entries/observations you want see.

In [347]:
type(is_huge)

pandas.core.series.Series

In [351]:
brics[[True,True,False,True,False]] == brics[is_huge]

Country  GDP(2012)  capital  area  population
BR     True       True     True  True        True
RU     True       True     True  True        True
CH     True       True     True  True        True

A simple one-liner, nesting the definition of is_huge inside the bracket:

In [352]:
brics[brics['area'] > 8]

Country  GDP(2012)   capital    area  population
BR  Brazil   1.921176  Brasilia   8.516       200.4
RU  Russia   4.024086    Moscow  17.100       143.5
CH   China   7.863736   Beijing   9.597      1657.0

#### Using numpy.logical_and() to join comparison operators and still have it work element-wise.
Keep in mind that simply using python's and, or, not keywords will not work for whole dataframes, but since pandas is based on numpy, we can use the numpy equivalent methods.  Below is how we get rows that satisfy (10 > area > 8).

In [353]:
import numpy as np
np.logical_and(brics['area'] > 8, brics['area'] < 10)

BR     True
RU    False
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [354]:
brics[np.logical_and(brics['area'] > 8, brics['area'] < 10)]

Country  GDP(2012)   capital   area  population
BR  Brazil   1.921176  Brasilia  8.516       200.4
CH   China   7.863736   Beijing  9.597      1657.0

## 5.4 - Loops

## 5.5 - Case Study: Hacker Statistics

In [ ]:
def random_walk(walk_length):
    cumulative_steps = []
    

## 5.6 - Netflix Mini-Project

# UNIT 6 | PY201: INTERMEDIATE PYTHON I

# UNIT 7 | PY202: INTERMEDIATE PYTHON II

## 7.1	Developing a Data Science Toolkit

## 7.2	User-defined functions

## 7.3	Scoping Things Out

## 7.4	Lambda Functions and Error Handling

## 7.5	Iterators

## 7.6	List Comprenensions